\documentclass[a4paper]{article}
\usepackage{graphicx, verbatim}
\usepackage[utf8]{inputenc}
%%\usepackage[czech]{babel}
\usepackage{amsmath,amssymb,amsthm,mathrsfs,amsfonts}
\usepackage{epigraph}

\usepackage{wasysym}
\setlength{\textwidth}{6.5in}
\setlength{\textheight}{9in}
\setlength{\oddsidemargin}{0in}
\setlength{\evensidemargin}{0in}
\setlength{\topmargin}{-1.5cm}
\renewcommand*{\theenumi}{\thesection.\arabic{enumi}}
\renewcommand*{\theenumii}{\theenumi.\arabic{enumii}}
\numberwithin{equation}{subsection}
\usepackage{Sweave}
\usepackage{hyperref}
\hypersetup{
    colorlinks=true, %set true if you want colored links
    linktoc=all,     %set to all if you want both sections and subsections linked
    linkcolor=blue,  %choose some color if you want links to stand out
}
\newtheorem*{tip}{Tip}

\title{MetaMass: tools for mass spectrometry data meta-analysis}
\author{Jan Stuchlý, Fridtjof Lund-Johansen}
\begin{document}

\maketitle
\begin{center}
{\tt jan.stuchly@lfmotol.cuni.cz}
\end{center}
%%chunk
\section{Introduction}
The package provides tools for meta-analysis of subcellular proteomics data as described in Lund-Johansen et al Nature Methods 2016. The input is a tab-delimited text file with HGNC official human gene symbols as protein identifiers and normalized MS signal values measured in sub-cellular fractions from a single or multiple experiments. The program performs K-means clustering of the data, and the clusters are classified, scored and sorted on basis of their content of markers for subcellular localization.  The program automatically generates three types of output files: 1. A cdt file for visualization of the classified dataset as a heatmap in JavaTreeView, 2. A tab-delimited text file listing all protein identifiers with their assigned subcellular location together with annotations from the Human Protein Atlas, Uniprot and GO. 3. Precision-recall curves that provide information about the fit between the dataset and the marker set.

The package is useful for the following applications: a) Mapping the subcellular location of proteins. b) Assess the performance of subcellular fractionation methods. c) Assess the fit between subcellular proteomics data and information in annotation databases.

\noindent Required software:
\begin{itemize}
\item R (https://cran.r-project.org)
\item R Studio (https://www.rstudio.com) - for more user-friendly R-front-end
\item Install MetaMass - Within R-studio use the command: install\_github("stuchly/MetaMass")
\item Open user manual from within R: vignette("MetaMass")
\item JavaTreeView (http://jtreeview.sourceforge.net/) - for visualisation
of heatmaps (the .cdt files - see below)
\end{itemize}
%% Installation:
%% Install devtools from R: \texttt{install.packages(``devtools'')}
%% load devtools: \texttt{library(devtools)}
%% Install MetaMass: \texttt{install_github(``stuchly/MetaMass'')}
%% load MetaMass: \texttt{library(MetaMass)}
%% see this vignette: \texttt{vignette("MetaMass")
\scriptsize
@
<<eval=false>>=
install.packages("devtools") ##  Install devtools from R
library(devtools) ## load devtools
install_github("stuchly/MetaMass") ## Install MetaMass
library(MetaMass) ## load MetaMass
vignette("MetaMass") ## see more detailed vignette
@ %def
\normalsize
\section{Data input}

On input users provide a tab-delimited text file containing the MS data (data.frame). For detailed instructions on data formatting see Lund-Johansen et al. Nature Methods 2016. Briefly:
\begin{itemize}
\item The first column must contain official gene symbols (HGNC)
\item All other columns should contain numerical data only
\item Values for individual sets of fractions should be normalized
\item MS data from different experiments should be separated by a blank column.
\end{itemize}

\section{Output}
To generate output files, the user must specify the parameter output="name" and inspect the results outside R. In this case four files will be created in the working directory.
\begin{itemize}
\item name\_table.txt - spreadsheet with separate columns for protein identifiers, markers used for the analysis, full text annotations from the Human Protein Atlas, Uniprot and GO,  protein overlap in the groups, cluster assignment, assigned location, precision of subcellular mapping,  and finally, the MS normalized signal values. For an example, see supplementary Table 1.15 in Lund-Johansen et al. Nature Methods 2016.
\item name\_pr.pdf - precision-recall curves for the markers.
\item name\_pr\_abs.pdf - number of assigned proteins versus the precision of the subcellular mapping.
\item name\_javatree.cdt - heatmap to be visualized in the Java TreeView application. Each line is annotated by the protein ID, marker/annotation (Annot=;if present for this protein) and assigned location (assign=;assigned location for cluster containing this protein)
\end{itemize}

\section{Metadata}
The package is distributed with MS data that can be used to reproduce
the results in the paper or serve as a reference for user-supplied
data. These data are referred to as Metadata, and they correspond to
those in supplementary Table 1.3 in the article. Metadata are not
(by default) clustered or classified, but used as reference in heatmaps and the mapping table. To see a list of the meta-data files, use the command \texttt{?Metadata}
Their location on the computer can be found via the system.file function.
The Metadata can be used as \texttt{data.frame} or if the user want to
open then in a spreadsheet editor their location on the computer can
be found via \texttt{system.file} function.
\scriptsize
@
<<>>=
filename<-system.file("extdata","Bileck.txt",package="MetaMass")
filename
@ %def
\normalsize
\section{Walk-through}
In this section we provide a detailed description how to analyze MS data files. Users should first retrieve supplementary table 1 from Lund-Johansen et al. Nature Methods 2016 and follow instructions in the table to retrieve the following datasets as described in text box within the tables: Data\_Fig2a (Table 1.13), Datasets 4, 9 and 10 (Table 1.3, use the filtering option explained in the text box in columns in columns BO:BY). The files should be saved in a new folder (e.g. named “Test”) as separate tab-delimited text files and named “Data\_Fig2a.txt” “study4.txt”, “study9.txt” and “study10.txt”, respectively. Set the folder “Test” as the working directory in R-studio. (type ctrl shift H and navigate to the folder).

\subsection{Analysis option 1}
\label{opt1}
Most users are likely to prefer to use the default option, since the command is very simple.  The command below will generate a heatmap similar to that in Fig.2a in the article, a data table similar to that in supplementary Table 1.15 and a precision recall curves for the fit between the default marker set and the data. Users only need to modify the names for the input and output files to work with other datasets.
\scriptsize
@
<<eval=false>>=
analyze.MSfile(MSfile = "Data_Fig2a.txt", overlap=2, output = "Fig2a")
@ %def
\normalsize
\noindent Explanation:\\
\textit{analyze.MSfile} : the function used in all analyses (no modifications, allowed)\\
\textit{MSfile}: input file (to modify : “my\_input\_file.txt”)\\
\textit{Overlap}: minimum protein overlap in datasets (use 1 if only one dataset is to be analyzed)\\
\textit{Output}: prefix to name output files.  (to modify “my\_file\_name”)\\

\noindent Default settings:\\
\textit{Metadata}:  The “Christoforou” dataset was chosen as default because of the high resolution and coverage of proteins in cytoplasmic organelles.\\
\textit{Cluster size}: The program automatically adjusts the numbers of clusters to obtain an average of five proteins per cluster.\\
\textit{Marker set}: The marker set “Study 1+ Uniprot/GOoverlap” described in the article provided the best fit with MS data. This set was therefore selected as default.\\
The output files are found in the working directory. All output files have the prefix “Fig2a”. The Fig2a.cdt file is a heatmap file (JavaTreeView), the Fig2a\_table.txt is the classification result table (e.g. Excel), and the Fig2a\_pr.pdf and Fig2a\_pr\_abs.pdf contain precision-recall curves (e.g. Acrobat Reader).

\subsection{Analysis option 2}
Generate recall precision curves for multiple different marker sets (i.e similar to those in Fig. 2b in the article, but with traces for all available marker sets).
\scriptsize
@
<<eval=false>>=
analyze.MSfile(MSfile = "Data_Fig2a.txt", overlap=2, output = "Fig2acurves", markers = c(3:8))
@ %def
\normalsize

\noindent Explanation:\\
The command \textit{markers = c(3:8)} specifies use of all marker sets that are included in the package.  The marker sets are numbered as follows: 3= Christoforou+UniprotGO\_overlap, 4= UniprotGO\_overlap, 5 UniprotGO\_sum, 6= HPA\_Single\_supportive, 7= HPA\_Single\_uncertain, Set 8 is a slim version of 3, where cytoskeleton is referred to as cytosol, and proteins in cytoplasmic organelles and membranes are referred to as membrane. This set is useful to assess precision of methods used to separate cytoplasm, membranes and nuclei. (article Fig. 2c).
\begin{tip}Most of the text is similar to the command used in \hyperref[opt1]{5.1}. Use the arrow up key in R-studio to bring this command back. Simply modify the last part: output= "Fig2acurves", markers = c(3:7)) and type enter.\end{tip}
\noindent Result: The Recall-Precision curves show results obtained with all the marker sets for the data in Fig 2a. The table contains columns with the mapping result obtained with all marker sets. The function generates a single heatmap corresponding to the first marker set, which in this case is the default marker set. The heatmap is therefore the same as that obtained using the default option.


\subsection{Analysis option 3}
Generate heatmaps to compare the mapping result obtained using different marker sets.
\scriptsize
@
<<eval=false>>=
analyze.MSfile(MSfile = "Data_Fig2a.txt", overlap=2, output = "Fig2aUniGOoverlap", markers = 4)
@ %def
\normalsize

\begin{tip}
Type arrow-up to bring back the command from example  \hyperref[opt1]{5.2}, and modify the text after output as indicated in the command. Repeat this approach with all marker sets up to 7. With this approach it takes very little time to make heatmaps for all marker sets.
\end{tip}
\noindent Result:\\
The heatmap generated using the Uniprot/GO overlap set marker set is rather similar to that obtained using the Study 1 + Uniprot/GO marker set (Fig2a article, example \hyperref[opt1]{5.1}). With markers from the Human Protein Atlas, the area in the map assigned to the nucleus is much larger, and many of the proteins assigned to the nucleus are found in the cytoplasmic fractions. The heatmap obtained with the “uncertain” annotations from the HPA has very little structure. Thus, there is very little correspondence with the MS data. In the output table, the mapped locations are listed alongside annotations from Uniprot, GO, and the HPA.
\subsection{Analysis option 4}
Generate recall-precision curves for single datasets (i.e. similar to Fig. 2c in article)
\scriptsize
@
<<eval=false>>=
analyze.MSfile(MSfile = "study4.txt", overlap=1, output = "study4", markers = 8)
@ %def
\normalsize
\noindent Result: The recall response curves for cytosol and nucleus are similar to those for study 4 in Fig2a.

\subsection{Analysis option 5}

Perform a meta-analysis of datasets 4, 9 and 10.
\scriptsize
@
<<eval=false>>=
analyze.MSfile(MSfile = c("study4.txt","study9.txt", "study10.txt"),  overlap=2, output = "study4910")
@ %def
\normalsize

\noindent Explanation:\\
c(”study4.txt”,”study9.txt”, ”study10.txt”) is used to merge data from multiple files into one analysis.\\

\noindent Result:\\
The fractionation methods used in studies 4, 9 and 10 have limited resolution. However, combined they have high resolution. Thus, study 4 has high resolution of mitochondria, but poor separation of ER and nuclei. Study 9 has good separation of cytoplasmic organelles and nuclei, but no resolution of ER, mitochondria or cytosol. Study 9 has good resolution of cytosol, membranes and nuclei, but does not discriminate ER from mitochondria. When the datasets are combined, they complement each other.


\end{document}
